version: '3.7'

services:

  nexus3:
    container_name: nexus3
    image: sonatype/nexus3
    ports:
      - 8081:8081
    volumes:
      - ./nexus-data/admin.password:/nexus-data/admin.password
    networks:
      - nexus3

networks:
  nexus3:
    name: nexus3
